app_name = "library_management_system"
app_title = "Library Management System"
app_publisher = "sandra"
app_description = "Library management system"
app_email = "sandrageorgee251@gmail.com"
app_license = "mit"

# -----------------------------
# Desk Module Configuration
# -----------------------------
add_to_apps_screen = [
    {
        "name": "library_management_system",
        "logo": "/assets/library_management_system/logo.png",
        "title": "Library Management System",
        "route": "/library_management_system",
    }
]

# -----------------------------
# App includes (optional)
# -----------------------------
app_include_js = []
app_include_css = []

# -----------------------------
# API: Whitelisted Methods
# -----------------------------
# These allow your Book API functions to be accessed externally
override_whitelisted_methods = {
    # Book APIs (search, list, create, update, delete, bulk import)
    "library_management_system.api.bulk_import_books":
        "library_management_system.api.bulk_import_books",

    "library_management_system.api.get_books":
        "library_management_system.api.get_books",

    "library_management_system.api.search_books":
        "library_management_system.api.search_books",

    "library_management_system.api.create_book":
        "library_management_system.api.create_book",

    "library_management_system.api.update_book":
        "library_management_system.api.update_book",

    "library_management_system.api.delete_book":
        "library_management_system.api.delete_book",
}

# -----------------------------
# Everything below stays unchanged
# -----------------------------

# required_apps = []

# include js, css files in header of desk.html
# app_include_css = "/assets/library_management_system/css/library_management_system.css"
# app_include_js = "/assets/library_management_system/js/library_management_system.js"

# include js, css files in header of web template
# web_include_css = "/assets/library_management_system/css/library_management_system.css"
# web_include_js = "/assets/library_management_system/js/library_management_system.js"

# website_theme_scss = "library_management_system/public/scss/website"

# Additional autogenerated comments left untouched for compatibility
